---
title: "Gov 50 Final Project"
author: "Talulah Ratcliffe"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project Proposal 
Is the inclusion of 'Diversity, Equity and Inclusion' within K-12 School District mission statements affected by party, race and income? In this study, I plan to examine the extent to which socioeconomic and partisan factors of a given school district in the US, influences whether or not values of diversity, equity and inclusion are included in their mission statements. 

I hypothesize that there will not only be a correlation between party and race/income, but that Republican districts with higher proportions of white, upper-class students, will be less likely to include Diversity, Equity and Inclusion within their mission statements. 

As seen through the Affirmative Action case this year, conservative ideology tends to value race-blind and, more generally, identity-blind policies and values. Policies (with a school Mission statement replicating the effect of a legal imposition) which attempt to fundamentally interfere with objective principles which equally apply to all, are usually rejected by Republicans, as well as privileged racial and economic groups. 

My representative sample is comprised of 1314 mission statements from regular public school districts, whose mission statements were published online as of November 2022. The schools were chosen from a comprehensive list maintained by the National Center for Education Statistics. My unit of analysis is a Mission Statement. The explanatory variable of interest is whether values of diversity, equity or inclusion are included. The variable is coded = 1 for included, and = 0 for excluded. My outcome variables are the party of the district - Republican or Democrat. This is reflected through whether the majority of residents voted for Donald Trump or Joe Biden in the 2020 presidential election, and is calculated using 2020 General Election Results Disaggregated to 2020 Census Blocks Datasets available through the Redistricting Data Hub. Population data includes median income and share of white residents, and was accessed from the 2015-2019 American Community Survey estimates published by the Census Bureau. 

If I observe more inclusion of diversity, inclusion and equity values in Mission Statements within Republican, upper-class and predominately white districts, this would provide support for my hypothesis. On the other hand, if I observe more inclusion of diversity, inclusion and equity values in Mission Statements within Democratic, lower-class and predominately non-white school districts, this would provide evidence against my hypothesis. 

